### ISSUE TITLE
Bootcommerce child - css not working 

### ISSUE THREAD

**Issue by MartynaC** [bootscore/bootcommerce-child#35]
hello, 

I have used this child theme in my other projects and never had an issue with this. But this time, I have installed the freshly downloaded version of your theme and I can't seem to make any changes in CSS. 
The simplest example: 
here is what I have in my bscore.custom.scss
h1 {
    color: $primary;
}
and that is what I have in my bscore.variables.scss: 
$primary: #00FF00;

obviously I have tried using just the "red" color etc - the CSS is not getting loaded in any way, my H1 is black as it was. 

In my console I can see:       
GET https://mydomain.pl/wp-content/themes/bootcommerce-child-main/css/main.css?ver=197001010000 net::ERR_ABORTED 404

By default this file is called "main.scss" and it is in the correct folder, so I have attempted to change the name of this file, to "main.css" but it did not help.

**Comment by crftwrk** [comment]
Solved? However it seems that is scssphp stops workíng for whatever reason. Use dev_mode https://github.com/bootscore/bootscore/issues/228

**Comment by MartynaC** [comment]
Hey, yes, solved :) 
I was going to post the solution - so it seems like I had to change "bootstrap.min.css" to "bootstrap.min.scss", I also tried with the dev_mode, but after the above change I have switched it off and it all seems to work correctly now.

**Comment by crftwrk** [comment]
Changing `main.scss` to `bootstrap.min.scss` means that you are downgrading your 5.2 child to bootScore 5.1.3.1 or older.  When starting a new project, you should always latest release https://github.com/bootscore/bootscore/releases, https://github.com/bootscore/bootcommerce-child/releases. Actual 5.2.2.1 is much more stable than 5.1.3.1 and has a lot updated WC templates.
