### ISSUE TITLE
 Template name is incorrrect

### ISSUE THREAD

**Issue by sweetappleuk** [bootscore/bootcommerce-child#37]
Currently style.css is defined as below and hence this child-theme is broken.:
  
Template:     bootscore-main

Should be

 Template:     bootscore

**Comment by crftwrk** [comment]
`bootscore-main` is the theme folder of the main-theme. What's wrong here?

**Comment by sweetappleuk** [comment]
Ah. I did a git clone https://github.com/bootscore/bootscore.git on the parrent theme that unzip into /themes/bootscore. 

Perhaps on the parent theme docs you should explicitly say that it should beb unzipped into a folder named bootscore-main to avoid any potential confusion?

**Comment by crftwrk** [comment]
> Perhaps on the parent theme docs you should explicitly say that it should beb unzipped into a folder named bootscore-main to avoid any potential confusion?

This is how a child in WP works https://developer.wordpress.org/themes/advanced-topics/child-themes/. If you rename main-theme folder, then you have to change this in child as well. But this makes no sense, use always `bootscore-main` folder in main-theme to avoid issues with compiler or whatever.

Direct download link https://github.com/bootscore/bootscore/archive/refs/heads/main.zip
